<?xml version="1.0" encoding="utf-8"?><Database Name="DBDeveloperJI" Class="DBClassDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=developerji.com;Initial Catalog=DBDeveloperJI;User ID=UserJI" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DBDeveloperJIConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.JICategoriaPost" Member="JICategoriaPosts">
    <Type Name="JICategoriaPost">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PostID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CategoriaID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="JIPost_JICategoriaPost" Member="JIPost" ThisKey="PostID" OtherKey="PostID" Type="JIPost" IsForeignKey="true" />
      <Association Name="JICategoria_JICategoriaPost" Member="JICategoria" ThisKey="CategoriaID" OtherKey="CategoriaID" Type="JICategoria" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.JIUser" Member="JIUsers">
    <Type Name="JIUser">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Login" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pass" Type="System.Data.Linq.Binary" DbType="VarBinary(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="NicName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Url" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Registred" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ActivadoKey" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DisplayName" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Association Name="JIUser_JIPost" Member="JIPosts" ThisKey="UserID" OtherKey="UserID" Type="JIPost" />
    </Type>
  </Table>
  <Table Name="dbo.JIOptions" Member="JIOptions">
    <Type Name="JIOption">
      <Column Name="OptionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OptionName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="OptionValue" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.JIPostMeta" Member="JIPostMetas">
    <Type Name="JIPostMeta">
      <Column Name="MetaID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PostID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MetaKey" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="JIPost_JIPostMeta" Member="JIPost" ThisKey="PostID" OtherKey="PostID" Type="JIPost" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.JIPost" Member="JIPosts">
    <Type Name="JIPost">
      <Column Name="PostID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PostDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PostDateModificado" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PostContent" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="PostTitle" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="PostStatus" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PostCommentCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PostImage" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="PostParent" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CategoriaPrincipal" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Clave" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="JIPost_JICategoriaPost" Member="JICategoriaPosts" ThisKey="PostID" OtherKey="PostID" Type="JICategoriaPost" />
      <Association Name="JIPost_JIPostMeta" Member="JIPostMetas" ThisKey="PostID" OtherKey="PostID" Type="JIPostMeta" />
      <Association Name="JIPost_JIComment" Member="JIComments" ThisKey="PostID" OtherKey="PostID" Type="JIComment" />
      <Association Name="JIUser_JIPost" Member="JIUser" ThisKey="UserID" OtherKey="UserID" Type="JIUser" IsForeignKey="true" />
      <Association Name="JICatalogoGeneral_JIPost" Member="JICatalogoGeneral" ThisKey="Clave" OtherKey="Clave" Type="JICatalogoGeneral" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.JICatalogoGeneral" Member="JICatalogoGenerals">
    <Type Name="JICatalogoGeneral">
      <Column Name="CatalogoID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Clave" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Etiqueta" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Tipo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="JICatalogoGeneral_JIPost" Member="JIPosts" ThisKey="Clave" OtherKey="Clave" Type="JIPost" />
    </Type>
  </Table>
  <Table Name="dbo.vPostMenu" Member="vPostMenus">
    <Type Name="vPostMenu">
      <Column Name="MenuID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CategoriaID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CategoriaName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(2500) NOT NULL" CanBeNull="false" />
      <Column Name="PostID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PostDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PostDateModificado" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PostContent" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="PostTitle" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="PostStatus" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PostCommentCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PostImage" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="PostParent" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CategoriaPrincipal" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Clave" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MenuStatus" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Tipo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.JICategorias" Member="JICategorias">
    <Type Name="JICategoria">
      <Column Name="CategoriaID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(2500) NOT NULL" CanBeNull="false" />
      <Column Name="MenuID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Visible" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="JICategoria_JICategoriaPost" Member="JICategoriaPosts" ThisKey="CategoriaID" OtherKey="CategoriaID" Type="JICategoriaPost" />
      <Association Name="JIMenu_JICategoria" Member="JIMenu" ThisKey="MenuID" OtherKey="MenuID" Type="JIMenu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.vPost" Member="vPosts">
    <Type Name="vPost">
      <Column Name="PostID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PostTitle" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="PostCommentCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NicName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PostDateModificado" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CategoriaPrincipal" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="PostContent" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.JIComment" Member="JIComments">
    <Type Name="JIComment">
      <Column Name="CommentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PostID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Author" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="AuthorEmail" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="AuthorUrl" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="AuthorIP" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="CommentDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CommentContent" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="CommentParent" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="JIPost_JIComment" Member="JIPost" ThisKey="PostID" OtherKey="PostID" Type="JIPost" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.vPostMeta" Member="vPostMetas">
    <Type Name="vPostMeta">
      <Column Name="MetaKey" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="PostID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PostDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PostDateModificado" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PostContent" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="PostTitle" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="PostStatus" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PostCommentCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PostImage" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="PostParent" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CategoriaPrincipal" Type="System.String" DbType="VarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Clave" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.JIMenu" Member="JIMenu">
    <Type Name="JIMenu">
      <Column Name="MenuID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MenuParent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MenuStatus" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Orden" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Clave" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Tipo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Imagen" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="PostID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Contacto" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="JIMenu_JICategoria" Member="JICategoria" ThisKey="MenuID" OtherKey="MenuID" Type="JICategoria" />
    </Type>
  </Table>
  <Table Name="dbo.JISuscripcion" Member="JISuscripcion">
    <Type Name="JISuscripcion">
      <Column Name="SuscripcionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(650) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="fecha" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>